 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'


 jobs:
   unittests:
     name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 90
     strategy:
       matrix:
         #os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         os: ['macos-latest'] 
         environment-file: [ci/envs/38-PYPI.yaml, ci/envs/38-PYPI-PLUS.yaml, ci/envs/38-GIT.yaml, ci/envs/38-GIT-PLUS.yaml]
     steps:
       - uses: actions/checkout@v2
       - name: Clear freespace
         run: |
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            df -h
       - uses: goanpeca/setup-miniconda@v1
         with:
            miniconda-version: 'latest'
            auto-update-conda: true
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
       - shell: bash -l {0}
         run: conda info --all
       - shell: bash -l {0}
         run: conda list
       - shell: bash -l {0}
         run: py.test -v spaghetti --cov=spaghetti --doctest-modules --cov-config=.coveragerc --cov-report=xml
       - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: spaghetti-codecov
